version: "3.1"

services:
  api:
    build:
      context: .
      dockerfile: debug.Dockerfile
    volumes:
      - ${PWD}:/src-root
    environment:
      RUST_LOG: info
      DATABASE_URL: postgres://mydb:changeme@db:5432/mydb
      REDIS_URL: redis://cache:6379/
      JWT_SECRET: ITS A SECRET
      ARGON_SECRET: ITS ANOTHER SECRET
    ports:
      - 3535:3535
    depends_on:
      - db
      - cache
    restart: always
  
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mydb
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: mydb
    restart: always

  cache:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
